export { default as DidDocumentService, ElemDidDocument, KeyVault, LocalKeyVault } from './DidDocumentService'
export { RegistryResolveDidService } from './RegistryResolveDidService'
export { default as DigestService } from './DigestService'
export { default as JwtService } from './JwtService'
export { default as KeysService } from './KeysService'
export { default as MetricsService } from './MetricsService'
