export { default as DidDocumentService } from './DidDocumentService'
export { default as ElemDidDocumentService } from './DidDocumentService/ElemDidDocumentService'
export { default as ElemAnchoredDidDocumentService } from './DidDocumentService/ElemAnchoredDidDocumentService'
export { default as JoloDidDocumentService } from './DidDocumentService/JoloDidDocumentService'
export { default as PolygonDidDocumentService } from './DidDocumentService/PolygonDidDocumentService'
export { KeyVault } from './DidDocumentService'
export { LocalKeyVault } from './DidDocumentService'
export { default as DigestService } from './DigestService'
export { default as KeysService } from './KeysService'
export { default as MetricsService } from './MetricsService'
export { EncryptionService } from './EncryptionService'
