const ONE_MINUTE_IN_MS = 60 * 1000
const ONE_HOUR_IN_MS = ONE_MINUTE_IN_MS * 60
export const DEFAULT_MAX_TOKEN_VALID_IN_MS = ONE_HOUR_IN_MS * 12
export const DEFAULT_REQUEST_TOKEN_VALID_IN_MS = ONE_MINUTE_IN_MS
