require('./KeysService.test')
require('./DidDocumentService.test')
require('./DigestService.test')
require('./EncryptionService.test')
require('./ElemDidDocumentLocalResolver.test')
require('./KeyDidDocumentLocalResolver.test')
