require('./ApiService.test')
require('./EmailIssuerService.test')
require('./CognitoService.test')
require('./PhoneIssuerService.test')
require('./WalletStorageService.test')
require('./MetricsService.test')
