export enum Service {
  METRICS = 'affinity-metrics',
  REGISTRY = 'affinity-registry',
  SFF_ISSUER = 'sff-issuer',
  VAULT = 'affinidi-vault',
  BLOOM_VAUlT = 'bloom-vault',
  CLOUD_WALLET_API = 'cloud-wallet-api',
  ISSUER = 'affinity-issuer',
  WALLET_BACKEND = 'affinity-wallet-backend',
  VERIFIER = 'affinity-verifier',
  ONBOARDING_BACKEND = 'affinity-onboarding-backend',
  MESSAGES = 'affinidi-messages',
  REVOCATION_API = 'revocation-api',
  USER_AUTH = 'user-auth',
  SCHEMA_MANAGER = 'affinidi-schema-manager',
}
