on:
  pull_request:
    branches:
      - master
name: CodeClimate Workflow
jobs:
  codeClimateTrigger:
    name: CodeClimate Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Set env vars
        id: vars
        run: echo "::set-output name=pr_key::$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')"
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install npm v8
        run: npm install -g npm@8
      - name: Check for skipped tests
        run: |
            [ $(find . -maxdepth 6 -name *.test.ts -exec grep \\.only {} \; | wc -l) -eq 0 ];
      - name: Download cc-test-reporter
        run: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - uses: actions/upload-artifact@v3
        with:
          name: test-reporter
          path: ./tmp/cc-test-reporter
      - name: Install dependencies
        run: npm ci
      - name: Link
        run: npm run link
      - name: Bootstrap
        run: npm run bootstrap
      - name: Check Diff
        run: git diff --exit-code
      - name: Lerna checkLicenses
        run: npm run checkLicenses
      - name: Build
        run: npm run build
      - name: Lint packages
        run: npm run lint
      - uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          TEST_SECRETS: ${{secrets.INTEGRATION_TEST_SECRETS}}
          TESTMAIL_API_KEY: ${{secrets.TESTMAIL_API_KEY}}
          TESTMAIL_NS: ${{secrets.TESTMAIL_NS}}
          TEST_PUBLIC_KEY_STR: ${{secrets.TEST_PUBLIC_KEY_STR}}
        with:
          coverageCommand: npm run test:coverage:codeclimate
      - name: Generate and Upload Test Coverage
        run: |
            $GITHUB_WORKSPACE/tmp/cc-test-reporter sum-coverage $GITHUB_WORKSPACE/tmp/codeclimate.*.json -p $(ls -1q $GITHUB_WORKSPACE/tmp/codeclimate.*.json | wc -l) -d -o tmp/codeclimate.total.json
            $GITHUB_WORKSPACE/tmp/cc-test-reporter upload-coverage -i $GITHUB_WORKSPACE/tmp/codeclimate.total.json
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
