name: Public Packages publish workflow

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install npm v7
        run: npm install -g npm@7
      - name: Install dependencies
        run: npm install
      - name: Lerna link
        run: npm run link
        env:
          NODE_AUTH_TOKEN: ${{secrets.PUBLIC_NPM_NODE_AUTH_TOKEN}}
      - name: Lerna bootstrap
        run: npm run bootstrap
        env:
          NODE_AUTH_TOKEN: ${{secrets.PUBLIC_NPM_NODE_AUTH_TOKEN}}
      - name: Lerna checkLicenses
        run: npm run checkLicenses
        env:
          NODE_AUTH_TOKEN: ${{secrets.PUBLIC_NPM_NODE_AUTH_TOKEN}}
      - name: Run tests
        run: npm test
        env:
          NODE_AUTH_TOKEN: ${{secrets.PUBLIC_NPM_NODE_AUTH_TOKEN}}
          TEST_SECRETS: ${{secrets.INTEGRATION_TEST_SECRETS}}
          TESTMAIL_API_KEY: ${{secrets.TESTMAIL_API_KEY}}
          TESTMAIL_NS: ${{secrets.TESTMAIL_NS}}
      - name: Run integration tests
        run: npm run test:integration
        env:
          NODE_AUTH_TOKEN: ${{secrets.PUBLIC_NPM_NODE_AUTH_TOKEN}}
          TEST_SECRETS: ${{secrets.INTEGRATION_TEST_SECRETS}}
          TESTMAIL_API_KEY: ${{secrets.TESTMAIL_API_KEY}}
          TESTMAIL_NS: ${{secrets.TESTMAIL_NS}}
      - name: Build the package
        run: npm run build
        env:
          NODE_AUTH_TOKEN: ${{secrets.PUBLIC_NPM_NODE_AUTH_TOKEN}}
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: "https://registry.npmjs.org"
          scope: "@affinidi"
      - name: Install npm v7
        run: npm install -g npm@7
      - name: Publish to npmjs.org
        run: npm run publish from-package -- --yes --registry https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{secrets.PUBLIC_NPM_NODE_AUTH_TOKEN}}
          TEST_SECRETS: ${{secrets.INTEGRATION_TEST_SECRETS}}
          TESTMAIL_API_KEY: ${{secrets.TESTMAIL_API_KEY}}
          TESTMAIL_NS: ${{secrets.TESTMAIL_NS}}
